# Generated by Django 4.0.5 on 2022-07-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
