# Generated by Django 4.0.5 on 2022-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_storefront_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
